# Generated by Django 4.1.5 on 2023-02-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
